name: "node"
services:
  node:
    image: "11notes/node:22.14.0"
    read_only: true
    environment:
      TZ: "Europe/Zurich"
    volumes:
      - "node:/node"
    networks:
      frontend:
    restart: "always"

volumes:
  node:

networks:
  frontend: